### ISSUE TITLE
authorize

### ISSUE THREAD

**Issue by eloiup** [g07kore/Google-Earth-Engine-Python-Examples#2]
its a simple change. no need for **_authorize_ee.ipynb_** no more.
just:

```
import ee
ee.Initialize()
```

**Comment by renelikestacos** [comment]
Oh cool @eloiup didnt know. i wasn't working with the Python lately. Thanks man

**Comment by eloiup** [comment]
the notebooks were quite helpful, ty! i just started trying out the api, got a bunch of doubts about it, sent you an email, if its not too much trouble any help is appreciated
